---
- name: Set the hostname to 'devbox'
  hostname:
      name: devbox

- name: Change timezone to America/Chicago
  timezone:
    name: America/Chicago

- name: Update package cache and install package updates
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    purge: yes

- name: Install common packages
  apt:
    pkg:
      - sendmail
      - unzip
      - zip
