---
- name: Add ondrej/php ppa
  apt_repository:
    repo: ppa:ondrej/php

- name: Add ondrej/nginx ppa
  apt_repository:
    repo: ppa:ondrej/nginx

- name: Install php and nginx
  apt:
    pkg:
      - nginx
      - php-common
      - php-cli
      - php-bcmath
      - php-fpm
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-pgsql
      - php-tokenizer
      - php-xml
      - php-zip
      - unzip
      - zip

- name: Download composer and place in /usr/local/bin
  get_url:
    url: https://getcomposer.org/composer-stable.phar
    dest: /usr/local/bin/composer
    mode: '0755'

- name: Add vendor bin to path in .zshrc
  lineinfile:
    dest: '/home/{{linux_username}}/.zshrc'
    line: 'export PATH=$PATH:/home/{{linux_username}}/.config/composer/vendor/bin'
